apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontangular
  namespace: ishtar
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: ishtar-angular
        image: gcr.io/yescloud/ishtatfront
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: ishtar
  labels:
    run: front
spec:
  type: LoadBalancer
  ports:
  - port: 4200
    protocol: TCP
  selector:
    app: angular
---
