steps:
timeout: 1800s
- name: gcr.io/cloud-builders/docker
   
  args:
    - build
    - '-t'
    - '$_IMAGE_NAME:$COMMIT_SHA'
    - .
    - '-f'
    - $_DOCKERFILE_NAME
  dir: $_DOCKERFILE_DIR
  id: Build
